# Generated by Django 6.1 on 2026-08-26 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalrun',
            name='selected_google_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_runs', to='integrations.connectedaccount'),
        ),
        migrations.AlterField(
            model_name='connectedaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('disconnected', 'Disconnected'), ('quota_exhausted', 'Quota Exhausted'), ('error', 'Error')], default='active', max_length=30),
        ),
    ]
