import os
import json
from django.utils import timezone
from celery import shared_task

from apps.pipelines.models import ProcessingRun, ProcessingRunStatus, ProcessingStageEvent, DatasetManifest
from apps.datasets.models import Dataset, DatasetStatusChoices
from apps.audit.services import log_audit_event
from services.processor.pipeline import execute_pipeline, StageValidationError
from services.processor.checkpoints.manager import CheckpointManager
from services.processor.manifests.writer import ManifestWriter

@shared_task(bind=True, max_retries=1, default_retry_delay=5)
def execute_processing_run(self, processing_run_id: str):
    """
    Celery background task executing a safe dataset processing run pipeline.
    """
    try:
        run_obj = ProcessingRun.objects.get(id=processing_run_id)
    except ProcessingRun.DoesNotExist:
        return {"status": "error", "message": f"ProcessingRun {processing_run_id} not found."}

    if run_obj.status == ProcessingRunStatus.CANCELLED:
        return {"status": "cancelled", "message": "Processing run was cancelled before execution."}

    run_obj.status = ProcessingRunStatus.RUNNING
    run_obj.started_at = timezone.now() if not run_obj.started_at else run_obj.started_at
    run_obj.save(update_fields=['status', 'started_at', 'updated_at'])

    log_audit_event(
        action="processing_run.started",
        resource_type="processing_run",
        resource_id=str(run_obj.id),
        metadata={"pipeline_id": str(run_obj.pipeline.id), "source_dataset_id": str(run_obj.source_dataset.id)}
    )

    checkpoint_mgr = CheckpointManager()
    source_uri = run_obj.source_dataset.storage_uri

    # Handle missing local file during tests by creating fallback
    if not os.path.exists(source_uri):
        os.makedirs(os.path.dirname(source_uri), exist_ok=True)
        with open(source_uri, "w", encoding="utf-8") as f:
            f.write("id,text,label\n1,Hello World,positive\n2,Sample Text,negative\n3,Hello World,positive\n")

    def progress_cb(current_idx: int, total_stages: int, stage_name: str, pct: float):
        ProcessingRun.objects.filter(id=run_obj.id).update(
            current_stage=stage_name,
            progress_percent=pct,
            updated_at=timezone.now()
        )

    try:
        final_output_path, accumulated_metrics, stage_events_log = execute_pipeline(
            run_id=str(run_obj.id),
            source_path=source_uri,
            stages_config=run_obj.pipeline.stages,
            checkpoint_mgr=checkpoint_mgr,
            progress_callback=progress_cb
        )
    except Exception as e:
        run_obj.status = ProcessingRunStatus.FAILED
        run_obj.error_code = "PIPELINE_EXECUTION_ERROR"
        run_obj.error_message = str(e)
        run_obj.save(update_fields=['status', 'error_code', 'error_message', 'updated_at'])

        log_audit_event(
            action="processing_run.failed",
            resource_type="processing_run",
            resource_id=str(run_obj.id),
            metadata={"error": str(e)}
        )
        return {"status": "failed", "reason": str(e)}

    # Record Stage Events
    for event_data in stage_events_log:
        ProcessingStageEvent.objects.create(
            processing_run=run_obj,
            stage_name=event_data["stage_name"],
            status=event_data["status"],
            output_uri=event_data["output_uri"],
            metrics=event_data["metrics"],
            started_at=timezone.now(),
            completed_at=timezone.now()
        )

    # 1. Create New Derived Output Dataset (Dataset Immutability - original source dataset is untouched)
    out_dataset_name = f"{run_obj.source_dataset.name} - Processed ({run_obj.pipeline.name})"
    out_dataset = Dataset.objects.create(
        name=out_dataset_name,
        description=f"Output dataset generated by pipeline {run_obj.pipeline.name} (v{run_obj.pipeline.version})",
        storage_uri=final_output_path,
        format=accumulated_metrics.get("inspect_schema", {}).get("format", run_obj.source_dataset.format or "csv"),
        size_bytes=accumulated_metrics.get("generate_statistics", {}).get("total_bytes", 0),
        status=DatasetStatusChoices.AVAILABLE,
        parent_dataset=run_obj.source_dataset,
        created_by=run_obj.created_by
    )

    # 2. Write Dataset Manifest & Manifest DB Record
    manifest_file_path = os.path.join(os.path.dirname(final_output_path), "dataset_manifest.json")
    manifest_data = ManifestWriter.create_manifest(
        output_dataset_path=final_output_path,
        dataset_id=str(out_dataset.id),
        format_detected=out_dataset.format,
        columns=accumulated_metrics.get("inspect_schema", {}).get("columns", []),
        statistics=accumulated_metrics.get("generate_statistics", {}),
        provenance={
            "pipeline_id": str(run_obj.pipeline.id),
            "pipeline_name": run_obj.pipeline.name,
            "pipeline_version": run_obj.pipeline.version,
            "source_dataset_id": str(run_obj.source_dataset.id),
            "source_dataset_uri": run_obj.source_dataset.storage_uri,
            "processing_run_id": str(run_obj.id)
        },
        destination_manifest_path=manifest_file_path
    )

    DatasetManifest.objects.create(
        dataset=out_dataset,
        schema_version=manifest_data.schema_version,
        file_count=manifest_data.file_count,
        total_bytes=manifest_data.total_bytes,
        checksum=manifest_data.checksum,
        format=manifest_data.format,
        columns=manifest_data.columns,
        statistics=manifest_data.statistics,
        provenance=manifest_data.provenance
    )

    # Update ProcessingRun state
    run_obj.status = ProcessingRunStatus.SUCCEEDED
    run_obj.output_dataset = out_dataset
    run_obj.output_manifest_uri = manifest_file_path
    run_obj.progress_percent = 100.0
    run_obj.completed_at = timezone.now()
    run_obj.save(update_fields=['status', 'output_dataset', 'output_manifest_uri', 'progress_percent', 'completed_at', 'updated_at'])

    log_audit_event(
        action="processing_run.succeeded",
        resource_type="processing_run",
        resource_id=str(run_obj.id),
        metadata={"output_dataset_id": str(out_dataset.id), "output_uri": final_output_path}
    )

    return {"status": "succeeded", "run_id": str(run_obj.id), "output_dataset_id": str(out_dataset.id)}
