# Generated by Django 6.1 on 2026-08-26 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_dataset_parent_dataset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(default='1.0', max_length=50)),
                ('file_count', models.IntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('format', models.CharField(blank=True, max_length=50)),
                ('columns', models.JSONField(default=list)),
                ('statistics', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifest', to='datasets.dataset')),
            ],
            options={
                'db_table': 'pipelines_datasetmanifest',
            },
        ),
        migrations.CreateModel(
            name='PipelineDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('stages', models.JSONField(default=list, help_text='List of configured pipeline stages')),
                ('resource_policy', models.JSONField(default=dict, help_text='Resource limits for container execution')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pipelines_pipelinedefinition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('validating', 'Validating'), ('running', 'Running'), ('checkpointing', 'Checkpointing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused'), ('retrying', 'Retrying')], db_index=True, default='draft', max_length=50)),
                ('current_stage', models.CharField(blank=True, max_length=100)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('input_manifest_uri', models.CharField(blank=True, max_length=1024)),
                ('output_manifest_uri', models.CharField(blank=True, max_length=1024)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_runs', to=settings.AUTH_USER_MODEL)),
                ('output_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_processing_runs', to='datasets.dataset')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pipelines.pipelinedefinition')),
                ('source_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_processing_runs', to='datasets.dataset')),
            ],
            options={
                'db_table': 'pipelines_processingrun',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('input_uri', models.CharField(blank=True, max_length=1024)),
                ('output_uri', models.CharField(blank=True, max_length=1024)),
                ('metrics', models.JSONField(default=dict)),
                ('log_uri', models.CharField(blank=True, max_length=1024)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='pipelines.processingrun')),
            ],
            options={
                'db_table': 'pipelines_processingstageevent',
                'ordering': ['created_at'],
            },
        ),
    ]
