# Generated by Django 6.1 on 2026-08-26 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('framework', models.CharField(max_length=100)),
                ('framework_version', models.CharField(blank=True, max_length=50)),
                ('model_format', models.CharField(max_length=50)),
                ('checksum', models.CharField(max_length=128)),
                ('metadata', models.JSONField(default=dict, help_text='Hyperparameters, dataset lineage, metrics summary')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('validating', 'Validating'), ('approved', 'Approved'), ('archived', 'Archived'), ('rejected', 'Rejected')], db_index=True, default='registered', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_versions', to='artifacts.artifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'models_registry_modelversion',
                'ordering': ['-created_at'],
            },
        ),
    ]
