# Generated by Django 6.1 on 2026-08-26 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_registry', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='training_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_models', to='training.trainingrun'),
        ),
        migrations.AlterUniqueTogether(
            name='modelversion',
            unique_together={('name', 'version')},
        ),
    ]
