# Generated by Django 6.1 on 2026-08-26 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_dataset_parent_dataset'),
        ('pipelines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('backend', models.CharField(default='demo', max_length=50)),
                ('container_image', models.CharField(default='kaya/ml-trainer:pytorch-2.2', max_length=255)),
                ('container_digest', models.CharField(blank=True, max_length=255)),
                ('configuration', models.JSONField(default=dict, help_text='Hyperparameters and model settings')),
                ('resource_policy', models.JSONField(default=dict, help_text='CPU/GPU resource boundaries')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('scheduled', 'Scheduled'), ('preparing', 'Preparing'), ('running', 'Running'), ('checkpointing', 'Checkpointing'), ('paused', 'Paused'), ('cancelling', 'Cancelling'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], db_index=True, default='draft', max_length=50)),
                ('current_epoch', models.IntegerField(default=0)),
                ('current_step', models.IntegerField(default=0)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('best_metric', models.FloatField(blank=True, null=True)),
                ('best_metric_name', models.CharField(blank=True, max_length=100)),
                ('checkpoint_uri', models.CharField(blank=True, max_length=1024)),
                ('output_model_uri', models.CharField(blank=True, max_length=1024)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_runs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='datasets.dataset')),
                ('processing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_runs', to='pipelines.processingrun')),
            ],
            options={
                'db_table': 'training_trainingrun',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.IntegerField()),
                ('epoch', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('split', models.CharField(default='train', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='training.trainingrun')),
            ],
            options={
                'db_table': 'training_trainingmetric',
                'ordering': ['step'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.IntegerField()),
                ('epoch', models.IntegerField()),
                ('storage_uri', models.CharField(max_length=1024)),
                ('checksum', models.CharField(max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('metrics', models.JSONField(default=dict)),
                ('status', models.CharField(default='valid', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='training.trainingrun')),
            ],
            options={
                'db_table': 'training_trainingcheckpoint',
                'ordering': ['-created_at'],
            },
        ),
    ]
