# Generated by Django 6.1 on 2026-08-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_recovery_codes_hashed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recovery_codes_hashed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totp_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totp_secret_encrypted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
