# Generated by Django 6.1 on 2026-08-26 07:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.TextField()),
                ('provider', models.CharField(db_index=True, default='generic_http', max_length=50)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('storage_uri', models.CharField(blank=True, max_length=500, null=True)),
                ('temporary_path', models.CharField(blank=True, max_length=500, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('downloaded_size_bytes', models.BigIntegerField(default=0)),
                ('checksum_algorithm', models.CharField(default='sha256', max_length=20)),
                ('expected_checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('extract', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('resolving', 'Resolving'), ('downloading', 'Downloading'), ('validating', 'Validating'), ('extracting', 'Extracting'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], db_index=True, default='pending', max_length=30)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('current_speed_bytes', models.FloatField(default=0.0)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'downloads_download',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', 'created_at'], name='downloads_d_created_4f3684_idx'), models.Index(fields=['status', 'created_at'], name='downloads_d_status_50555b_idx'), models.Index(fields=['provider', 'created_at'], name='downloads_d_provide_d41384_idx')],
            },
        ),
    ]
