"""Execution adapter that lets a persistent VM dispatch a job to Colab CLI."""

import fcntl
import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Callable


class ColabExecutionError(RuntimeError):
    pass


_PIPELINE_JOB_TYPES = {
    "ingest_documents",
    "generate_candidates",
    "run_quality_audit",
    "freeze_dataset",
    "train_qlora",
    "sync_to_drive",
}


def _build_colab_pipeline_code(job_type: str, payload: dict) -> str:
    """Build the small launcher executed *inside* the selected Colab kernel.

    The VM only invokes ``colab exec`` and records the result.  Source checkout,
    dependency installation, data processing and artifact writes all happen in
    Colab, with the collection root stored on the mounted Drive.
    """
    safe_payload = dict(payload)
    safe_payload.pop("code", None)
    payload_json = json.dumps(safe_payload)
    repository = os.environ.get("KAYA_COLAB_REPOSITORY", "https://github.com/stayhubindia/Kaya_Compute_Hub.git")
    data_root = safe_payload.get("colab_data_root", "/content/drive/MyDrive/Kaya_Compute_Hub/data")
    return f'''import json
import os
import subprocess
import sys
from pathlib import Path

REPOSITORY = {repository!r}
REPO_DIR = Path('/content/kaya-compute-hub')
DATA_ROOT = {str(data_root)!r}
PAYLOAD = json.loads({payload_json!r})

if not Path('/content/drive/MyDrive').is_dir():
    raise RuntimeError('Google Drive is not mounted in this Colab session. Mount Drive from Console or Integrations first.')

if not REPO_DIR.exists():
    subprocess.run(['git', 'clone', '--depth', '1', REPOSITORY, str(REPO_DIR)], check=True)

requirements = REPO_DIR / 'requirements-pipeline.txt'
subprocess.run([sys.executable, '-m', 'pip', 'install', '--quiet', '-r', str(requirements)], check=True)
sys.path.insert(0, str(REPO_DIR))
os.environ['DATA_ROOT'] = DATA_ROOT

from services.worker.executors.pipeline_executor import run_pipeline_executor

def report(percent, stage, message):
    print(f'KAYA_PROGRESS={{percent}}|{{stage}}|{{message}}', flush=True)

result = run_pipeline_executor({job_type!r}, PAYLOAD, report)
print('KAYA_RESULT=' + json.dumps(result, default=str), flush=True)
'''


def _colab_binary() -> str:
    configured = os.environ.get("COLAB_CLI_BIN", "").strip()
    if configured:
        return configured
    candidate = Path(os.sys.executable).parent / "colab"
    return str(candidate) if candidate.exists() else (shutil.which("colab") or "colab")


def _safe_session_name(value: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9_-]+", "-", value.strip()).strip("-")
    return (value or "kaya-colab-worker")[:64]


def _activate_account(account) -> None:
    if account is None:
        raise ColabExecutionError("A connected Google account is required for Colab execution.")
    if account.status != "active":
        raise ColabExecutionError(f"Selected Google account is '{account.status}', not active.")

    token_dir = Path.home() / ".config/colab-cli"
    token_dir.mkdir(parents=True, exist_ok=True)
    token_file = token_dir / "token.json"
    payload = {}
    raw_credentials = getattr(account, "get_credential_json", lambda: "")()
    if raw_credentials:
        try:
            parsed = json.loads(raw_credentials)
            if isinstance(parsed, dict):
                payload.update(parsed)
        except (TypeError, ValueError):
            pass
    # `google-colab-cli` accepts the complete authorized-user JSON created by
    # its own login command. A bare access/refresh token can be used by the
    # Drive API, but cannot create a Colab runtime because the CLI also needs
    # the token's client metadata to refresh it without an interactive prompt.
    missing = [field for field in ("client_id", "client_secret", "refresh_token") if not payload.get(field)]
    if missing:
        raise ColabExecutionError(
            "Selected account is Drive-only, not a usable Colab CLI account. "
            "Re-import the complete token.json generated by the official Colab CLI "
            f"(missing: {', '.join(missing)})."
        )
    payload["token"] = payload.get("token") or account.get_access_token()
    payload["refresh_token"] = payload.get("refresh_token") or account.get_refresh_token()
    payload["scopes"] = payload.get("scopes") or account.scopes or []
    if account.token_expiry:
        payload["expiry"] = account.token_expiry.isoformat().replace("+00:00", "Z")
    if not payload["token"] and not payload["refresh_token"]:
        raise ColabExecutionError("Selected account has no usable Colab CLI credentials. Import its token.json from the account's Colab CLI.")

    temp_file = token_dir / f"token.{os.getpid()}.tmp"
    temp_file.write_text(json.dumps(payload), encoding="utf-8")
    temp_file.chmod(0o600)
    temp_file.replace(token_file)


def _cli(colab_bin: str, *args: str) -> list[str]:
    # The official Colab CLI reads the active token.json directly. No browser
    # callback or app registration is used by the VM.
    return [colab_bin, *args]


def run_colab_job(job, update_progress_cb: Callable[[int, str, str], None]) -> dict:
    """Create/reuse a Colab session and execute the job's Python code from the VM."""
    payload = job.payload or {}
    code = payload.get("code", "").strip()
    if not code and job.job_type in _PIPELINE_JOB_TYPES:
        code = _build_colab_pipeline_code(job.job_type, payload)
    if not code:
        raise ColabExecutionError("Colab job payload must contain Python code.")

    session_name = _safe_session_name(payload.get("session_name", f"kaya-{str(job.id)[:8]}"))
    accelerator = str(payload.get("accelerator", "T4")).upper()
    timeout_seconds = min(max(int(payload.get("timeout_seconds", 1800)), 30), 21600)
    colab_bin = _colab_binary()
    lock_path = Path(tempfile.gettempdir()) / "kaya-colab-cli.lock"

    update_progress_cb(5, "colab_auth", "Activating selected Google account for Colab dispatch")
    with lock_path.open("w") as lock_file:
        fcntl.flock(lock_file, fcntl.LOCK_EX)
        _activate_account(job.selected_google_account)

        update_progress_cb(15, "colab_session", f"Checking Colab session '{session_name}'")
        sessions = subprocess.run(
            _cli(colab_bin, "sessions"), capture_output=True, text=True, timeout=20
        )
        if session_name not in sessions.stdout:
            create_cmd = _cli(colab_bin, "new", "-s", session_name)
            if accelerator in {"T4", "L4", "A100", "H100"}:
                create_cmd.extend(["--gpu", accelerator])
            elif accelerator in {"TPU", "V5E1", "V6E1"}:
                create_cmd.extend(["--tpu", "v5e1" if accelerator == "TPU" else accelerator.lower()])
            created = subprocess.run(create_cmd, capture_output=True, text=True, timeout=120)
            if created.returncode != 0:
                message = (created.stderr or created.stdout).strip()
                raise ColabExecutionError(f"Colab session allocation failed: {message}")

        update_progress_cb(30, "colab_running", "Python task is running inside the Colab runtime")
        script_path = None
        try:
            with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as script:
                script.write(code)
                script_path = script.name
            result = subprocess.run(
                _cli(colab_bin, "exec", "-s", session_name, "-f", script_path, "--timeout", str(timeout_seconds)),
                capture_output=True,
                text=True,
                timeout=timeout_seconds,
            )
        except subprocess.TimeoutExpired as exc:
            raise ColabExecutionError(
                f"Colab task exceeded its {timeout_seconds}-second VM timeout; resume from the latest Drive checkpoint."
            ) from exc
        finally:
            if script_path:
                Path(script_path).unlink(missing_ok=True)

    if result.returncode != 0:
        raise ColabExecutionError((result.stderr or result.stdout or "Colab execution failed").strip())

    update_progress_cb(100, "completed", "Colab task completed; VM stored only status and logs")
    return {
        "execution_target": "colab",
        "session_name": session_name,
        "accelerator": accelerator,
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
    }
