# Generated by Django 6.1 on 2026-08-26 06:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('idle', 'Idle'), ('busy', 'Busy'), ('draining', 'Draining'), ('unhealthy', 'Unhealthy')], db_index=True, default='offline', max_length=50)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('cpu_count', models.IntegerField(default=0)),
                ('memory_bytes', models.BigIntegerField(default=0)),
                ('gpu_count', models.IntegerField(default=0)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workers_worker',
                'ordering': ['-last_heartbeat_at'],
            },
        ),
    ]
