# Generated by Django 6.1 on 2026-08-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='allocated_gpu_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='available_gpu_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='cuda_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='gpu_memory_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='gpu_model',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
