# Generated by Django 6.1 on 2026-08-26 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('job_type', models.CharField(choices=[('download', 'Download'), ('extraction', 'Extraction'), ('preprocessing', 'Preprocessing'), ('notebook', 'Notebook'), ('training', 'Training'), ('evaluation', 'Evaluation')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('leased', 'Leased'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], db_index=True, default='draft', max_length=50)),
                ('priority', models.IntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'), models.Index(fields=['job_type'], name='jobs_job_job_typ_f6c220_idx'), models.Index(fields=['created_by'], name='jobs_job_created_c4a970_idx'), models.Index(fields=['created_at'], name='jobs_job_created_1b3a4d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('created_by', 'idempotency_key'), name='unique_user_idempotency_key')],
            },
        ),
    ]
