# Generated by Django 6.1 on 2026-08-26 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='job',
            name='current_stage',
            field=models.CharField(blank=True, default='queued', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='job',
            name='progress_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
