# Generated by Django 6.1 on 2026-08-26 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_externalrun_selected_google_account_and_more'),
        ('jobs', '0002_job_assigned_worker_job_current_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='selected_google_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='integrations.connectedaccount'),
        ),
    ]
