# Generated by Django 6.1 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_selected_google_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(
                choices=[
                    ('download', 'Download'),
                    ('extraction', 'Extraction'),
                    ('preprocessing', 'Preprocessing'),
                    ('ingest_documents', 'Ingest Documents'),
                    ('generate_candidates', 'Generate Candidates'),
                    ('run_quality_audit', 'Run Quality Audit'),
                    ('freeze_dataset', 'Freeze Dataset'),
                    ('train_qlora', 'Train QLoRA'),
                    ('evaluate_model', 'Evaluate Model'),
                    ('sync_to_drive', 'Sync to Drive'),
                    ('custom_script', 'Custom Script'),
                    ('notebook', 'Notebook'),
                    ('training', 'Training'),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
