"""
Document Normalizer (Phase 3.3).
Performs deterministic text cleaning:
- Unicode normalization (NFKC)
- Font glyph / Private Use Area (PUA) mapping (MathType and Symbol font brackets/equations)
- Replacement character (\\ufffd) and PDF artifact repair
- Vertical math fragment reassembly (combining multi-line PDF math tokens into unified expressions)
- De-hyphenation of wrapped words (e.g., 'incom-\\n pressible' -> 'incompressible')
- Stripping running headers, footers, and standalone page number artifacts
- Preserving scientific notation, units, LaTeX equations, and code blocks
"""

from __future__ import annotations

import re
import unicodedata
from typing import Dict, List, Optional, Set


# Mapping for Private Use Area (PUA) math glyphs commonly generated by Word Equation Editor / MathType in PDFs
PUA_GLYPH_MAP: Dict[int, str] = {
    # Large brackets & parentheses (MathType bracket segments)
    0xF8EB: "(",
    0xF8EC: "(",
    0xF8ED: "(",
    0xF8EE: "{",
    0xF8EF: "|",
    0xF8F0: "}",
    0xF8F1: "[",
    0xF8F2: "[",
    0xF8F3: "[",
    0xF8F4: "|",
    0xF8F6: ")",
    0xF8F7: ")",
    0xF8F8: ")",
    0xF8F9: "}",
    0xF8FA: "|",
    0xF8FB: "{",
    0xF8FC: "]",
    0xF8FD: "]",
    0xF8FE: "]",
    # Symbol font mappings
    0xF072: " \\vec{} ",
    0xF026: " \\partial ",
    0xF075: " \\upsilon ",
    0xF0A7: " • ",
    0xF03D: " = ",
    0xF02B: " + ",
    0xF02D: " - ",
    0xF0B1: " ± ",
    0xF0B4: " × ",
    0xF0B8: " ÷ ",
}


class DocumentNormalizer:
    """Deterministic normalizer for raw extracted PDF/HTML text."""

    def __init__(
        self,
        unicode_form: str = "NFKC",
        dehyphenate: bool = True,
        strip_page_numbers: bool = True,
        strip_running_headers: bool = True,
        clean_pua_glyphs: bool = True,
        reassemble_math: bool = True,
    ):
        self.unicode_form = unicode_form
        self.dehyphenate = dehyphenate
        self.strip_page_numbers = strip_page_numbers
        self.strip_running_headers = strip_running_headers
        self.clean_pua_glyphs = clean_pua_glyphs
        self.reassemble_math = reassemble_math

    def map_pua_and_symbol_glyphs(self, text: str) -> str:
        """Translates Symbol font and MathType Private Use Area glyphs into standard ASCII/Unicode."""
        if not text:
            return ""

        chars = []
        for ch in text:
            code = ord(ch)
            if code in PUA_GLYPH_MAP:
                chars.append(PUA_GLYPH_MAP[code])
            elif 0xE000 <= code <= 0xF8FF:
                # Unmapped Private Use Area glyph — replace with space to avoid mojibake
                chars.append(" ")
            elif code == 0xFFFD:
                # Replacement character artifact — replace with space
                chars.append(" ")
            else:
                chars.append(ch)

        return "".join(chars)

    def normalize_unicode(self, text: str) -> str:
        """Normalizes Unicode characters to standard compatibility form."""
        if not text:
            return ""
        # Sanitize lone surrogate codepoints (U+D800 to U+DFFF) from complex PDF equations
        text = text.encode("utf-8", errors="surrogateescape").decode("utf-8", errors="replace")
        if self.clean_pua_glyphs:
            text = self.map_pua_and_symbol_glyphs(text)
        # Normalize NFKC but preserve standard linebreaks
        return unicodedata.normalize(self.unicode_form, text)

    def dehyphenate_text(self, text: str) -> str:
        """
        Recombines words split across lines by hyphens (e.g. 'incom-\\n pressible' -> 'incompressible').
        Does not break LaTeX commands, genuine hyphenated words, or markdown lists.
        """
        if not text:
            return ""
        # Match word ending with hyphen, newline, optional whitespace, followed by lowercase word continuation
        pattern = r"([a-zA-Z]{2,})-\s*[\r\n]+\s*([a-zA-Z]{2,})"
        text = re.sub(pattern, r"\1\2", text)

        # Match broken hyphen space artifact e.g. "word- word" -> "word-word"
        broken_hyphen_pattern = r"([a-zA-Z]{3,})-\s+([a-zA-Z]{3,})"
        text = re.sub(broken_hyphen_pattern, r"\1-\2", text)

        return text

    def strip_page_number_artifacts(self, text: str) -> str:
        """Removes standalone page numbers (e.g. '\\n 14 \\n' or 'Page 14 of 50')."""
        if not text:
            return ""
        # Standalone numbers on isolated lines
        text = re.sub(r"(?m)^\s*(?:Page\s+)?\d+(?:\s+of\s+\d+)?\s*$", "", text)
        # Trailing bracketed page numbers like [14] on isolated line
        text = re.sub(r"(?m)^\s*\[\d+\]\s*$", "", text)
        return text

    def strip_running_headers_and_footers(self, text: str, header_patterns: Optional[List[str]] = None) -> str:
        """
        Strips common repeating headers/footers found in arXiv and NPTEL course notes.
        """
        if not text:
            return ""
        # Standard arXiv header lines
        text = re.sub(r"(?im)^\s*arXiv:\d{4}\.\d{4,5}(?:v\d+)?\s*\[[a-zA-Z\.\-]+\]\s*.*$", "", text)
        # NPTEL running header lines
        text = re.sub(r"(?im)^\s*NPTEL\s*[-–—]\s*.*$", "", text)
        text = re.sub(r"(?im)^\s*Joint\s+Initiative\s+of\s+IITs\s+and\s+IISc\s*[-–—]?\s*.*$", "", text)
        text = re.sub(r"(?im)^\s*Funded\s+by\s+MHRD\s*[-–—]?\s*.*$", "", text)

        if header_patterns:
            for pat in header_patterns:
                text = re.sub(pat, "", text)

        return text

    def reassemble_math_fragments(self, text: str) -> str:
        """Reassembles vertical line-by-line formula fragments into unified math blocks."""
        if not text:
            return ""

        lines = text.split("\n")
        reconstructed = []
        math_buffer = []

        for line in lines:
            stripped = line.strip()
            if not stripped:
                if math_buffer:
                    buf_text = " ".join(math_buffer).strip()
                    if any(sym in buf_text for sym in ["∂", "∇", "∫", "∑", "ρ", "σ", "λ", "θ", "vec", "hat", "alpha", "beta", "psi"]) and (
                        "=" in buf_text or "+" in buf_text or "-" in buf_text or re.search(r"\(\d+(?:\.\d+)*\)", buf_text)
                    ):
                        reconstructed.append(f"\n$${buf_text}$$\n")
                    else:
                        reconstructed.extend(math_buffer)
                    math_buffer.clear()
                reconstructed.append("")
                continue

            # Check if this is a short math fragment line
            is_short_math = len(stripped) <= 25 and (
                stripped in ["(", ")", "[", "]", "{", "}", "+", "-", "=", "±", "×", "•", "∂", "∇", "∫", "∫∫", "∫∫∫", "cv", "s", "v", "ds", "dt", "dx", "dy", "dz", "dxdydz", "ρ", "σ", "λ", "θ"]
                or bool(re.match(r"^[∂∇\+\-=\(\)\[\]\s\d\w\u00b7·\^_/\\]+$", stripped))
                or bool(re.match(r"^\(\d+(?:\.\d+)*\)$", stripped))
            )

            if is_short_math and not (stripped.endswith(".") and len(stripped) > 6):
                math_buffer.append(stripped)
            else:
                if math_buffer:
                    buf_text = " ".join(math_buffer).strip()
                    if any(sym in buf_text for sym in ["∂", "∇", "∫", "∑", "ρ", "σ", "λ", "θ", "vec", "hat", "alpha", "beta", "psi"]) and (
                        "=" in buf_text or "+" in buf_text or "-" in buf_text or re.search(r"\(\d+(?:\.\d+)*\)", buf_text)
                    ):
                        reconstructed.append(f"\n$${buf_text}$$\n")
                    else:
                        reconstructed.extend(math_buffer)
                    math_buffer.clear()
                reconstructed.append(line)

        if math_buffer:
            buf_text = " ".join(math_buffer).strip()
            if any(sym in buf_text for sym in ["∂", "∇", "∫", "∑", "ρ", "σ", "λ", "θ", "vec", "hat", "alpha", "beta", "psi"]) and (
                "=" in buf_text or "+" in buf_text or "-" in buf_text or re.search(r"\(\d+(?:\.\d+)*\)", buf_text)
            ):
                reconstructed.append(f"\n$${buf_text}$$\n")
            else:
                reconstructed.extend(math_buffer)

        return "\n".join(reconstructed)

    def normalize_whitespace(self, text: str) -> str:
        """Normalizes multiple blank lines and tabs while preserving paragraph structure."""
        if not text:
            return ""
        # Replace non-breaking spaces with standard space
        text = text.replace("\u00a0", " ").replace("\u200b", "")
        # Replace 3 or more newlines with double newline
        text = re.sub(r"\n{3,}", "\n\n", text)
        # Replace multiple horizontal spaces on the same line with single space
        text = re.sub(r"[ \t]+", " ", text)
        return text.strip()

    def normalize(self, text: str) -> str:
        """Applies full normalization pipeline in deterministic order."""
        if not text:
            return ""
        t = self.normalize_unicode(text)
        if self.strip_running_headers:
            t = self.strip_running_headers_and_footers(t)
        if self.strip_page_numbers:
            t = self.strip_page_number_artifacts(t)
        if self.dehyphenate:
            t = self.dehyphenate_text(t)
        if self.reassemble_math:
            t = self.reassemble_math_fragments(t)
        t = self.normalize_whitespace(t)
        return t
